name: QC Update
description: Update the QC status of a variable.
title: "[QC]: "
labels: ["qc update"]
body:
  - type: markdown
    attributes:
      value: "## Please enter some information about the datasets that were checked:"
  - type: input
    id: variable_id
    attributes:
      label: Variable ID
      description: "What is the variable id? (see the dataset's filename)"
    validations:
      required: true
  - type: dropdown
    id: experiment_id
    attributes:
      label: Experiment
      description: Which experiment do the checked datasets correspond to?
      options:
        - all
        - historical
        - "scenarioSSP5-85"
      default: 0
    validations:
      required: true
  - type: input
    id: time_range
    attributes:
      label: Year Range
      description: '(Optional) Leave blank to select all time ranges for the specified experiment(s).'
      placeholder: yyyy-yyyy
  - type: dropdown
    id: pass_qc
    attributes:
      label: "Do the datasets pass the quality control checks?" 
      description: "If they do not pass, please explain below."
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true
  - type: textarea
    id: explanation
    attributes:
      label: "Explain the steps taken for quality control:"
    validations:
      required: true
